### ISSUE TITLE
Error message on get_all_online_servers

### ISSUE THREAD

**Issue by josephgbr** [CytraL/twp#23]
TWP 0.2.0 outputs the error message below. I don't know what this impacts, though.

> ERROR:__main__:Exception on /_get_all_online_servers [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/twp/twp.py", line 458, in get_all_online_servers
    return jsonify(twpl.get_tw_masterserver_list(PUBLIC_IP))
  File "/srv/twp/twpl/__init__.py", line 199, in get_tw_masterserver_list
    tw.run_loop()
  File "/srv/twp/twpl/teeworlds.py", line 458, in run_loop
    handler.call(address, data)
  File "/srv/twp/twpl/teeworlds.py", line 264, in call
    self.parse(data[len(self.data):])
  File "/srv/twp/twpl/teeworlds.py", line 271, in parse
    self.name = data.next().decode('utf8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 62-63: unexpected end of data

**Comment by CytraL** [comment]
Yes... i see this issue.... :\ i need upgrade the teeworlds library xD ... and i having problems with my VPS... servers stop working and twp can't kill them.... i need fix this annyoning bug!

Thx!
