### ISSUE TITLE
[0.3.1] Add funcsigs to requirements.txt

### ISSUE THREAD

**Issue by josephgbr** [CytraL/twp#36]
Right after updating dependencies from requirements.txt, I ran './run.py' and got the following error message:

> Traceback (most recent call last):
  File "/srv/twp/run.py", line 22, in <module>
    from twp import create_app, db_init
  File "/srv/twp/twp.py", line 19, in <module>
    import twpl
  File "/srv/twp/twpl/__init__.py", line 35, in <module>
    from configs import TWPConfig
  File "/srv/twp/twpl/configs.py", line 19, in <module>
    from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 4, in <module>
    from apscheduler.util import maybe_ref, datetime_to_utc_timestamp, utc_timestamp_to_datetime
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/util.py", line 15, in <module>
    from funcsigs import signature
ImportError: No module named funcsigs

After installing 'funcsigs', TWP works just fine.

**Comment by CytraL** [comment]
Thanks for report... I tested it in an new vps with Debian Jessie without problems :/... 

Added dependency.
